version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: millie
      POSTGRES_PASSWORD: millie
      PGDATA: /data
    volumes:
      - ./data:/data
      - /etc/passwd:/etc/passwd:ro
    ports:
      - 5432:5432
    user: 1000:1000
